# Generated by Django 3.1.5 on 2021-01-20 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indoorplants', '0004_merge_20210107_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='planttype',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myuser.myuser'),
            preserve_default=False,
        ),
    ]
